public enum DomainTag {
    IDENTIFIER, DECIMAL_INTEGER_CONSTANT, NON_DECIMAL_INTEGER_CONSTANT, SYMBOLIC_CONSTANT, STRING_SECTION, BOOLEAN_CONSTANT, REFERENCE_NULL_CONSTANT, SPACES, COMMENTS, END, NONE
}