public enum DomainTag {
    IDENTIFIER, DECIMAL_INTEGER_CONSTANT, NON_DECIMAL_INTEGER_CONSTANT, SYMBOLIC_CONSTANT, STRING_SECTION, BOOLEAN_CONSTANT,
    OR_XOR_OP, AND_OP, EQ_OP, ORD_OP, PLUS_OP, MINUS_OP, MUL_DIV_REM_OP, POWER_OP, NOT_OP,
    EQUAL, ASSIGN, DOT, LEFT_ARROW, COMMA, TILDE, BRACKETS, LEFT_PAR, RIGHT_PAR, SEMICOLON,
    KW_INT, KW_BOOL, KW_RETURN, KW_VOID, KW_CHAR, KW_LOOP, KW_THEN, KW_ELSE, KW_NULL, KW_WHILE, END, NONE
}